import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useMemo, useState } from "react";
import toast, { Toaster } from "react-hot-toast";

import { BlockchainTypes, CrossmintEVMWalletAdapter } from "@crossmint/connect";

import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
    const crossmintConnect = useMemo(
        () =>
            new CrossmintEVMWalletAdapter({
                // environment: C,
                chain: BlockchainTypes.ETHEREUM,
                projectId: "c8a38daa-6fc0-4c73-acbc-c62827cb72c3",
            }),
        []
    );
    const [wallet, setWallet] = useState<string>();
    const [signature, setSignature] = useState<string>();

    useEffect(() => {
        (async () => {
            const connected = await crossmintConnect.connect();
            console.log("connected", connected);
            setWallet(connected);
            console.log(connected);
        })();
    }, []);

    function signMessage() {
        crossmintConnect.signMessage("Hello World!").then((result) => {
            toast.success(result);
            setSignature(result);
        });
    }

    return (
        <>
            <Toaster />
            <div className={styles.container}>
                <Head>
                    <title>Create Next App</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                {wallet && <>Wallet: {wallet}</>}
                <button onClick={signMessage}>Sign Message</button>
                {signature && <>Signature: {signature}</>}
                {/* <WalletMultiButton />
            <SignMessage />
            <SendTransaction /> */}
            </div>
        </>
    );
};

export default Home;
